<a href="https://colab.research.google.com/github/hashamuddin1/Numpy.github.io/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

## **CREATING AN ARRAY**

In [ ]:
#ARRAY FUNCTION
#IT IS THE SIMPLEST WAY TO CREATE AN ARRAY
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
#WHEN WE GIVE A STRING VALUE THEN INT VALUE WILL CONVERT INTO STRING VALUE
b=np.array([1,2,3,"hasham"])
b

array(['1', '2', '3', 'hasham'], dtype='<U21')

In [ ]:
c=np.array([1,2,3,4.5])
c

array([1. , 2. , 3. , 4.5])

In [ ]:
d=np.array([1,2,3,4+2j])
d

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+2.j])

In [ ]:
#WE CAN ALSO CHANGE THE DATA TYPE OF AN ARRAY
e=np.array([1,2,3,4,5,6,7,8],dtype=complex)
e

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j])

In [ ]:
a=np.array([2,3,4,1,22],dtype=str)
a

array(['2', '3', '4', '1', '22'], dtype='<U2')

In [ ]:
#ARANGE FUNCTION
#WE WILL GIVE A RANGE AND IT WILL PRINT ACCORDING TO GIVEN RANGE
a=np.arange(10)
print(a)
b=np.arange(20)
print(b)
c=np.arange(1,6)
print(c)
#WE CAN ALSO GIVE STEP SIZE
d=np.arange(1,10,2)
print(d)
e=8
f=np.arange(e)
print(f)
g=np.arange(3,5)
print(g)
h=np.arange(10,1,-1)
print(h)
i=np.arange(8,dtype="complex")
print(i)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7]
[3 4]
[10  9  8  7  6  5  4  3  2]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j]


In [ ]:
#ZERO FUNCTION
#IT WILL PRINT ZEROS IN THE QUANTITY OF GIVEN NUMBER
a=np.zeros(5)
print(a)
b=np.zeros(10,dtype="int")
print(b)

[0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#ONES FUNCTION
#IT WILL PRINT ONE IN THE QUANTITY OF GIVEN NUMBER
a=np.ones(8)
print(a)
a=int(input("ENTER YOUR NUMBER: "))
b=np.ones(a)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1.]
ENTER YOUR NUMBER: 5
[1. 1. 1. 1. 1.]


In [ ]:
#IDENTITY FUNCTION
#IT WILL CREATE AN IDENTITY MATRIX IN THE NUMBER OF ROWS OF GIVEN NUMBER
a=np.identity(3)
print(a)
b=int(input("ENTER THE NUMBER: "))
c=np.identity(b)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
ENTER THE NUMBER: 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#EYE FUNCTION
#IT WILL PRINT 1 IN A DIAGONAL
a=np.eye(3)
print(a)
b=np.eye(3,2)
print(b)
#IF WE WILL GIVE K=n THEN IT WILL START PRINTING 1 BY nth COLUMN AND 1ST ROW
c=np.eye(3,2,k=1)
print(c)
#IF WE WILL GIVE K=-n THEN IT WILL START PRINTING 1 BY nth ROW AND 1ST COLUMN
d=np.eye(3,2,k=-1)
print(d)
z=np.eye(4,5,k=2)
print(z)
x=np.eye(5,3,k=-3)
print(x)
a=int(input("ENTER THE ROWS: "))
b=int(input("ENTER THE COLUMN: "))
c=np.eye(a,b)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[0. 1.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [1. 0.]
 [0. 1.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
ENTER THE ROWS: 4
ENTER THE COLUMN: 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
#LINSPACE FUNCTION FULL FORM LINEAR SPACE
#IT WILL PRINT NUMBERS IN THE QUANTITY OF GIVEN NUMBER IN NUM=n WITH EQUAL GAP AMONG THEM
a=np.linspace(1,100,num=5)
print(a)
b=int(input("ENTER ANY NUMBER: "))
#WE CHANGE THE DATATYPE
c=np.linspace(5,10,num=b,dtype="int")
print(c)
#IF WE DONOT WANT TO PRINT THE LAST NUMBER
d=np.linspace(1,10,num=5,endpoint=False)
print(d)
# IF WE WILL NOT GIVE THE NUM NUMBER THEN BYDEFAULT IT WILL PRINT 50 NUMBERS
e=np.linspace(1,10)
print(e)
#IF WE WANT TO SEE THE GAP VALUE
f=np.linspace(1,20,num=8,retstep=True)
print(f)

[  1.    25.75  50.5   75.25 100.  ]
ENTER ANY NUMBER: 4
[ 5  6  8 10]
[1.  2.8 4.6 6.4 8.2]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
(array([ 1.        ,  3.71428571,  6.42857143,  9.14285714, 11.85714286,
       14.57142857, 17.28571429, 20.        ]), 2.7142857142857144)


In [ ]:
#RANDOM FUNCTION
#RAND FUNCTION
#IT WILL PRINT ANY FLOAT RANDOM NUMBER
#help(np.random.rand)
a=np.random.rand(5)
print(a)
b=np.random.rand()
print(b)

[0.20663178 0.48379263 0.78116546 0.55029688 0.01600996]
0.5639420782026329


In [ ]:
#RANDN FUNCTION
#IT WILL PRINT ANY POSITIVE OR NEGATIVE RANDOM NUMBERS
a=np.random.randn()
print(a)
b=np.random.randn(3)
print(b)

-1.0709629195836567
[2.03905042 0.15415859 0.89817788]


In [ ]:
#RANDOM.CHOICE
#WE WILL GIVE PROBABILITY OF OBJECTS
d=["hasham","abu usama","bilal"]
e=np.random.choice(d,size=(4,4),p=[0.3,0.5,0.2])
print(e)

[['hasham' 'abu usama' 'hasham' 'hasham']
 ['hasham' 'hasham' 'hasham' 'abu usama']
 ['hasham' 'hasham' 'bilal' 'bilal']
 ['abu usama' 'hasham' 'abu usama' 'hasham']]


In [ ]:
#RANDOM.RANDINT
#IT WILL PRINT ANY INTEGAR RANDOM NUMBER BY GIVING RANGE
a=np.random.randint(44)
print(a)
b=np.random.randint(10,55)
print(b)


36
35


In [ ]:
#EMPTY FUNCTION
#PRINT ANY RANDOM NUMBER
a=np.empty(3)
print(a)
b=np.empty((3,2),dtype=int)
print(b)

[2.03905042 0.15415859 0.89817788]
[[                  0 4607182418800017408]
 [                  0                   0]
 [                  0                   0]]


In [ ]:
#DIAGONAL FUNCTION
#IT WILL PRINT THE GIVEN NUMBER IN A DIAGONAL
a=np.diag([1,8,5])
print(a)
#IF WE WANT TO SEE DIAGONAL NUMBER
print(np.diag(a))
a=int(input("HOW MANY TIMES YOU WANT TO GIVE A NUMBER: "))
d=[]
for b in range(a):
    c=eval(input("PRINT THE DIAGONAL NUMBERS: "))
    d.append(c)
print(d)
print(np.diag(d))

[[1 0 0]
 [0 8 0]
 [0 0 5]]
[1 8 5]
HOW MANY TIMES YOU WANT TO GIVE A NUMBER: 4
PRINT THE DIAGONAL NUMBERS: 5
PRINT THE DIAGONAL NUMBERS: 4
PRINT THE DIAGONAL NUMBERS: 3
PRINT THE DIAGONAL NUMBERS: 2
[5, 4, 3, 2]
[[5 0 0 0]
 [0 4 0 0]
 [0 0 3 0]
 [0 0 0 2]]


In [ ]:
#FULL FUNCTION
#IT WILL PRINT AN ARRAY THAT CONTAIN ONLY ONE PARTICULAR OBJECT
a=np.full(5,5)
print(a)
b=np.full((4,3),7)
print(b)
c=np.full(4,"a")
print(c)

[5 5 5 5 5]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
['a' 'a' 'a' 'a']


In [ ]:
#ZEROS_LIKE(a):CONVERT EXISTANCE ARRAY IN ZEROS FORM
a=np.array([1,22,3,4])
print(a)
print(np.zeros_like(a))
#ONES_LIKE(a):CONVERT ALL ENTRIES IN ONES
print(np.ones_like(a))
#EMPTY_LIKE(a):CONVERT ALL ENTRIES IN RANDOM NUMBERS
print(np.empty_like(a))
#FULL_LIKE(a):CONVERT ALL ENTRIES IN A PARTICULAR NUMBER
print(np.full_like(a,8))

[ 1 22  3  4]
[0 0 0 0]
[1 1 1 1]
[1 1 1 1]
[8 8 8 8]


## **TWO DIMENSIONAL ARRAY**

In [ ]:
a=np.array([[1,2,3,4,5],[6,5,4,3,5]])
print(a)
#IT IS COMPULSORY THAT ALL ROWS CONTAIN SAME NUMBER OF ELEMENTS
#OTHERWISE IT WILL GENERATE AN ERROR
#a=np.array([[3.2.1],[4,3]])
#print(a)#ERROR
b=np.zeros((4,3))
print(b)
c=np.ones((2,3))
print(c)
d=np.diag(["a","b","c"])
print(d)
e=np.identity(4)
print(e)
f=np.full((3,4),"k")
print(f)

[[1 2 3 4 5]
 [6 5 4 3 5]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[['a' '' '']
 ['' 'b' '']
 ['' '' 'c']]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[['k' 'k' 'k' 'k']
 ['k' 'k' 'k' 'k']
 ['k' 'k' 'k' 'k']]


## **THREE DIMENSIONAL ARRAY**

In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[2,3,1],[5,5,5]]])
print(a)
#IN ZEROS,FULL AND ONES FUNCTION: (NO:OF ARRAYS,NO:OF ROWS,NO:OF COLUMN)
b=np.zeros((3,4,2))
print(b)
c=np.ones((2,3,4))
print(c)
d=np.full((2,3,4),"h")
print(d)


[[[1 2 3]
  [4 5 6]]

 [[2 3 1]
  [5 5 5]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[['h' 'h' 'h' 'h']
  ['h' 'h' 'h' 'h']
  ['h' 'h' 'h' 'h']]

 [['h' 'h' 'h' 'h']
  ['h' 'h' 'h' 'h']
  ['h' 'h' 'h' 'h']]]


## **ATTRIBUTES**

In [ ]:
#NDIM:PRINT THE DIMENSION OF ARRAY
a=np.array([1,2,3,4,5])
print(a.ndim)
b=np.diag([2,5,8])
print(b.ndim)
c=np.array([[[1,2,3],[1,2,5]],[[5,6,7],[4,4,5]]])
print(c.ndim)
#SHAPE:PRINT THE SHAPE OF AN ARRAY,IF THEIR WILL BE 1 ROW THEN IT PRINTS NUMBER OF ENTRIES.
a=np.arange(10)
print(a.shape)
b=np.zeros_like([[[1,3,5],[2,2,2]],[[1,2,2],[3,9,9]]])
print(b)
print(b.shape)
#DTYPE:PRINT DATA TYPE AND BITS NUMBER
#FLOAT=64BITS
#INTEGAR=32BITS
a=np.array([1,2,3])
print(a.dtype)
b=np.array([3,4.6,3])
print(b.dtype)
c=np.array(["abcd"])
print(c.dtype)
#SIZE:PRINT NUMBER OF ENTRIES
a=np.array([1,2,3,4])
b=a.size
if b==4:
    print("OK")
else:
    print("NOT OK")
a=np.full((2,3),9)
print(a)
print(a.size)
b=np.diag([4,3,2])
print(b)
print(b.size)
c=np.zeros((2,5))
print(c.size)
#ITEMSIZE:PRINT NUMBER OF BYTE
#1 BYTE=8BITS
a=np.ones(5)
print(a.itemsize)
b=np.array([2,3,4])
print(b.itemsize)
c=np.array(["hasham"])
print(c.itemsize)

1
2
3
(10,)
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(2, 2, 3)
int64
float64
<U4
OK
[[9 9 9]
 [9 9 9]]
6
[[4 0 0]
 [0 3 0]
 [0 0 2]]
9
10
8
8
24


## **ARITHMETIC OPERATIONS**

In [ ]:

#ONE DIMENSION ARRAY
#IN ARRAY WE CAN ADD,SUBTRACT,MULTIPLY AND DIVIDE THE ENTRIES OF AN ARRAY BUT IN LIST WE CANNOT DO THIS
a=np.array([1,2,3])
b=np.array([6,8,3])
print(a+b)
c=[1,2,3]
d=[2,5,6]
print(c+d)
a=np.ones(8)
b=np.arange(1,9)
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a/b)
#TWO DIMENSION ARRAY
a=np.array([[1,2,3],[3,3,3]])
b=np.array([[2,1,2],[5,7,2]])
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a/b)
a=np.array([[[1,2],[3,3]],[[4,4],[9,1]]])
b=np.ones((2,2,2))
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a/b)
#THREE DIMENSIONAL ARRAY
a=np.array([[[1,2,3],[3,2,1]],[[3,3,3],[7,8,9]]])
b=np.array([[[3,3,3],[2,2,2]],[[1,1,1],[9,8,7]]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a+3)
print(a-3)
print(a*3)
print(a/3)
print(a//3)

[ 7 10  6]
[1, 2, 3, 2, 5, 6]
[2. 3. 4. 5. 6. 7. 8. 9.]
[ 0. -1. -2. -3. -4. -5. -6. -7.]
[1. 2. 3. 4. 5. 6. 7. 8.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125     ]
[[ 3  3  5]
 [ 8 10  5]]
[[-1  1  1]
 [-2 -4  1]]
[[ 2  2  6]
 [15 21  6]]
[[0 2 1]
 [0 0 1]]
[[0.5        2.         1.5       ]
 [0.6        0.42857143 1.5       ]]
[[[ 2.  3.]
  [ 4.  4.]]

 [[ 5.  5.]
  [10.  2.]]]
[[[0. 1.]
  [2. 2.]]

 [[3. 3.]
  [8. 0.]]]
[[[1. 2.]
  [3. 3.]]

 [[4. 4.]
  [9. 1.]]]
[[[1. 2.]
  [3. 3.]]

 [[4. 4.]
  [9. 1.]]]
[[[1. 2.]
  [3. 3.]]

 [[4. 4.]
  [9. 1.]]]
[[[ 4  5  6]
  [ 5  4  3]]

 [[ 4  4  4]
  [16 16 16]]]
[[[-2 -1  0]
  [ 1  0 -1]]

 [[ 2  2  2]
  [-2  0  2]]]
[[[ 3  6  9]
  [ 6  4  2]]

 [[ 3  3  3]
  [63 64 63]]]
[[[0.33333333 0.66666667 1.        ]
  [1.5        1.         0.5       ]]

 [[3.         3.         3.        ]
  [0.77777778 1.         1.28571429]]]
[[[0 0 1]
  [1 1 0]]

 [[3 3 3]
  [0 1 1]]]
[[[ 4  5

## **INDEXING**

In [ ]:
#ONE DIMENSION
#SAME LIKE A LIST
a=np.array([4,5,6,7,8])
print(a[3])
print(a[2])
print(a[:])
#TWO DIMENSION 
#D.B.N=DOUBLE BRACKET NOTATION
#VARIABLE_NAME[ROW][COLUMN]
a=np.array([[1,2,3,4],[3,3,3,3]])
print(a[0][2])
print(a[1][3])
print(a[-2][-3])
print(a[1])
print(a[:])#PRINT BOTH THE ARRAYS
#S.B.N=SINGLE BRACKET NOTATION
#VARIABLE_NAME[ROW,COLUMN]
a=np.array([[1,2,3,4],[3,4,3,5]])
print(a[1,1])
print(a[0])
print(a[:,:])
print(a[1,0])
print(a[-1,-3])
#THREE DIMENSION
#D.B.N=DOUBLE BRACKET NOTATION
#VARIABLE_NAME[ARRAY][ROW][COLUMN]
a=np.array([[[1,2,3],[4,3,2]],[[2,1,2],[3,4,5]]])
print(a)
print(a.ndim)
print(a[1][0][0])
print(a[1][1])#PRINT WHOLE ROW
print(a[0])#PRINT WHOLE ARRAY
print(a[-1][-2][-3])
print(a[:])
#S.B.N=SINGLE BRACKET NOTATION
#VARIABLE_NAME[ARRAY,ROW,COLUMN]
a=np.array([[[1,2,3],[4,3,2]],[[2,1,2],[3,4,5]]])
print(a[1,1,2])
print(a[0,1,1])
print(a[:,:,:])
print(a[0,1])
print(a[-1,-2,-3])

7
6
[4 5 6 7 8]
3
3
2
[3 3 3 3]
[[1 2 3 4]
 [3 3 3 3]]
4
[1 2 3 4]
[[1 2 3 4]
 [3 4 3 5]]
3
4
[[[1 2 3]
  [4 3 2]]

 [[2 1 2]
  [3 4 5]]]
3
2
[3 4 5]
[[1 2 3]
 [4 3 2]]
2
[[[1 2 3]
  [4 3 2]]

 [[2 1 2]
  [3 4 5]]]
5
3
[[[1 2 3]
  [4 3 2]]

 [[2 1 2]
  [3 4 5]]]
[4 3 2]
2


## **ADVANCED INDEXING OR FANCY INDEXING**

In [ ]:
#ADVANCED INDEXING
#INTEGAR INDEXING
#ONE DIMENSION
a=np.array([1,7,2,3,9,5])
b=[2,1,4]
c=a[b]
print(c)
print(a[b])
print(a[[2,4,3,1]])
print(a[[1,1,1,3,2,2]])

#TWO DIMENSION
#VARIABLE[ROW],[COLUMN]
a=np.array([[2,6,9,0,6],[2,1,3,5,6]])
b=[0,0,0,1,1],[1,2,2,2,3]
c=a[b]
print(c)
print(a[[0,0,0,1,1],[1,2,2,2,3]])

#THREE DIMENSION
#VARIABLE[ARRAY],[ROW],[COLUMN]
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[7,6,5]]])
print(a[[0,0,1,1],[0,1,0,1],[0,1,2,0]])


[2 7 9]
[2 7 9]
[2 9 3 7]
[7 7 7 3 2 2]
[6 9 9 3 5]
[6 9 9 3 5]
[1 5 9 7]


## **BOOLEAN INDEXING**

In [ ]:
#BOOLEAN INDEXING
#ONE DIMENSION
a=np.array([1,2,3,-1,-4-9,55])
print(a[a>0])
print(a[a>2])
print(a[a>2]*2)

#TWO DIMENSION
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[a>3])
print(a[a>2])
print(a[a>1]*2)

#THREE DIMENSION
a=np.array([[[3,2,1],[6,5,4]],[[9,8,7],[4,3,2]]])
print(a[a>3])
print(a[a>3]*2)

[ 1  2  3 55]
[ 3 55]
[  6 110]
[[1 2 3]
 [4 5 6]]
[4 5 6]
[3 4 5 6]
[ 4  6  8 10 12]
[6 5 4 9 8 7 4]
[12 10  8 18 16 14  8]


## **ARITHMETIC OPERATION USING BUILT-IN FUNCTIONS**

In [ ]:
#ONE DIMENSION ARRAY
a=np.array([2,5,3,6])
b=np.array([4,5,8,2])

#BETWEEN ARRAYS

print(np.add(b,a))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))

#WITH SCALAR VALUE

print(np.add(a,3))
print(np.subtract(a,3))
print(np.multiply(a,3))
print(np.divide(a,3))
print(np.mod(a,3))
print(np.power(a,3))

#TWO DIMENSION ARRAY
a=np.array([[3,2,1],[6,5,4]])
b=np.array([[2,3,1],[5,5,5]])

#BETWEEN ARRAYS

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))

#WITH SCALAR VALUE

print(np.add(a,3))
print(np.subtract(a,3))
print(np.multiply(a,3))
print(np.divide(a,3))
print(np.mod(a,3))
print(np.power(a,3))

#THREE DIMENSION
a=np.array([[[2,3,1],[5,4,3]],[[8,7,6],[0,9,8]]])
b=np.array([[[2,2,2],[1,1,1]],[[6,6,6],[4,5,6]]])

#BETWEEN ARRAYS

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))

#WITH SCALAR VALUE

print(np.add(a,3))
print(np.subtract(a,3))
print(np.multiply(a,3))
print(np.divide(a,3))
print(np.mod(a,3))
print(np.power(a,3))




[ 6 10 11  8]
[-2  0 -5  4]
[ 8 25 24 12]
[0.5   1.    0.375 3.   ]
[2 0 3 0]
[  16 3125 6561   36]
[5 8 6 9]
[-1  2  0  3]
[ 6 15  9 18]
[0.66666667 1.66666667 1.         2.        ]
[2 2 0 0]
[  8 125  27 216]
[[ 5  5  2]
 [11 10  9]]
[[ 1 -1  0]
 [ 1  0 -1]]
[[ 6  6  1]
 [30 25 20]]
[[1.5        0.66666667 1.        ]
 [1.2        1.         0.8       ]]
[[1 2 0]
 [1 0 4]]
[[   9    8    1]
 [7776 3125 1024]]
[[6 5 4]
 [9 8 7]]
[[ 0 -1 -2]
 [ 3  2  1]]
[[ 9  6  3]
 [18 15 12]]
[[1.         0.66666667 0.33333333]
 [2.         1.66666667 1.33333333]]
[[0 2 1]
 [0 2 1]]
[[ 27   8   1]
 [216 125  64]]
[[[ 4  5  3]
  [ 6  5  4]]

 [[14 13 12]
  [ 4 14 14]]]
[[[ 0  1 -1]
  [ 4  3  2]]

 [[ 2  1  0]
  [-4  4  2]]]
[[[ 4  6  2]
  [ 5  4  3]]

 [[48 42 36]
  [ 0 45 48]]]
[[[1.         1.5        0.5       ]
  [5.         4.         3.        ]]

 [[1.33333333 1.16666667 1.        ]
  [0.         1.8        1.33333333]]]
[[[0 1 1]
  [0 0 0]]

 [[2 1 0]
  [0 4 2]]]
[[[     4      9      1]
  [

## **COMPARISION BETWEEN ARRAYS**

In [ ]:
#IT WILL RETURN AN ARRAY OF BOOLEAN VALUES
a=np.array([1,2,3,4,55,66,77,88])
b=np.array([-1,-2,5,5,6,7,8,100])

print(a>b)
print(b>a)
print(a==b)
print(a!=b)

[ True  True False False  True  True  True False]
[False False  True  True False False False  True]
[False False False False False False False False]
[ True  True  True  True  True  True  True  True]


## **SLICING**

In [ ]:
#ONE DIMENSION
#SAME LIKE A LIST
a=[4,8,9,0,2,1]
print(a[2:5])
print(a[ : :-2])
print(a[ : :2])
print(a[-5: ])
print(a[1: ])
#TWO DIMENSION
#VARIABLE_NAME[ROW,COLUMN]
a=np.array([[2,3,1],[8,4,1]])
print(a)
print(a.ndim)
print(a[0][0:3])
print(a[1])
print(a[1,1:3])
print(a[0:2,1])
print(a[0:2,0])
print(a[-2: ,-2])
#THREE DIMENSION
#VARIABLE_NAME[ARRAY,ROW,COLUMN]
a=np.array([[[1,2,3],[4,5,6]],[[3,3,3],[2,3,1]]])
print(a[0,0:2,1:3])
print(a[:,:,:])#PRINT WHOLE A
print(a[0:2,0:2,1:3])


[9, 0, 2]
[1, 0, 8]
[4, 9, 2]
[8, 9, 0, 2, 1]
[8, 9, 0, 2, 1]
[[2 3 1]
 [8 4 1]]
2
[2 3 1]
[8 4 1]
[4 1]
[3 4]
[2 8]
[3 4]
[[2 3]
 [5 6]]
[[[1 2 3]
  [4 5 6]]

 [[3 3 3]
  [2 3 1]]]
[[[2 3]
  [5 6]]

 [[3 3]
  [3 1]]]


## **BRAODCASTING**

In [ ]:
#RULE 1:IF TWO ARRAY DIFFER IN THEIR NUMBER DIMENSION,THE SHAPE OF THE ONE WITH FEWER DIMENSION IS PADDED WITH ONE'S ON IT'S LEADING SIDE (LEFT SIDE).
#RULE 2:IF THE SHAPE OF THE TWO ARRAYS DOESNOT MATCH IN ANY DIMENSION,THE ARRAY WITH THE SHAPE EQUAL TO 1 IN THAT DIMENSION STRECTHED TO MATCH THE OTHER SHAPE. 
a=np.array([2,3,4,5,5,8])
b=np.array([6,4,3,3,6,7])
print(a+b)
#a=np.array([[3,3,3,3],[2,2,2,2],[1,1,1,1]])
#b=np.array([[1],[2],[3],[4]])
c=np.array([[1],[2],[3]])
d=np.array([1,2,3])
#print(a+b)#ERROR
print(a+c)
#print(a+d)#ERROR
c=np.array([3,2,1])
d=np.array([[2,1,3],[6,4,2]])
print(c+d)
e=np.array([1,2,3])
f=np.array([[1],[4],[6]])
print(e+f)
a=np.zeros((2,3,4))
b=np.ones((1,1))
print(a.shape)
print(b.shape)
print(a+b)


[ 8  7  7  8 11 15]
[[ 3  4  5  6  6  9]
 [ 4  5  6  7  7 10]
 [ 5  6  7  8  8 11]]
[[5 3 4]
 [9 6 3]]
[[2 3 4]
 [5 6 7]
 [7 8 9]]
(2, 3, 4)
(1, 1)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## **ARRAY MANIPULATION**

In [ ]:
#RESHAPING
#RESHAPE:WHEN WE USE RESHAPE FUNCTION,IT IS COMPULSORY THAT WE WILL GIVE DIMENSION OF SAME NUMBER OF ELEMENT PRESENT IN THE ORIGINAL ARRAY.IT MAKE COPY OF RESHAPE ARRAY.
a=np.arange(10)
print(a)
print(a.shape)
print(np.reshape(a,(5,2)))#BY DEFAULT THE ORDER IS C AND IT WILL GIVE ROW WISE RESHAPE.
print(np.reshape(a,(5,2),order="F"))#THE ORDER IS F SO IT WILL RETURN COLUMN WISE RESHAPE
print(a.reshape(2,5))
print(a.reshape((2,5),order="F"))
print(a.shape)#IT WILL RETURN 10 
c=a.reshape(2,5)
print(c)
#print(a.reshape(3,4))#ERROR
#RESIZE:IT RESIZE THE ARRAY, WE CAN GIVE THE DIMENSION OF MORE ELEMENTS ,SO IT WILL REPEAT THE ELEMENTS
a=np.arange(10)
print(np.resize(a,(3,4)))
print(np.resize(a,(5,5)))
#THERE IS NO OPTION OF ORDER F IN RESIZE FUNCTION
a.resize((5,5))
print(a)#IT WILL PRINT 0 ON EXTRA SPACE INSTEAD OF REPEATING AN ARRAY

#FLATTEN FUNCTION
#IT WILL MAKE A ND-ARRAY INTO ONE DIMENSION.IT RETURN A COPY OF ONE DIMENSION ARRAY
#SYNTAX
#array_name.flatten()BY DEFAULT ORDER IS C
#or
#array_name.flatten(order="F")
#import numpy as np
#TWO DIMENSION
a=np.array([[2,3,4],[5,4,3]])
print(a.flatten())
print(a.flatten(order="F"))
#print(np.flatten(a))#ERROR BECAUSE OF INCORRECT SYNTAX
#THREE DIMENSION
a=np.ones((2,3,4))
#print(a)
b=a.flatten()
print(b)
print(a)#IT WIL REMAIN THREE DIMENSIONAL
#RAVEL FUNCTION
#IT WILL CONVERT A ND-ARRAY INTO ONE DIMENSIONAL ARRAY.IT WILL RETURN A VIEW OF A ONE DIMENSIONAL ARRAY OR COPY WHEN NEEDED.
#SYNTAX
#array_name.ravel()
#or
#array_name.ravel(order="F")
#or
#np.ravel(a)
#np.ravel(a,order="F")
a=np.ones((2,3,4))
print(a)
print(np.ravel(a))
print(np.ravel(a,order='F'))
print(a.ravel())
print(a.ravel(order='F'))


#TRANSPOSE FUNCTION
#TWO DIMENSIONAL ARRAY
#IT WILL CHANGE ROWS INTO COLUMN AND COLUMN INTO ROWS.IT RETURN COPY OF AN TRANSPOSE ARRAY
#SYNTAX
#NP.TRANSPOSE(ARRAY_NAME,AXES)#BY DEFAULT AXES IS NONE
#OR
#ARRAY_NAME.TRANSPOSE(AXES)
#OR
#ARRAY_NAME.T   #BUT WITH THIS SYNTAX WE CANNOT GIVE AXES
a=np.array([[1,2,3,4],[7,6,5,4]])
print(a.shape)
print(np.transpose(a))
print(a.shape)#SHAPE REMAIN SAME AS ORIGINAL ARRAY
b=np.arange(10)
b.resize((4,3))
print(b)
print(b.transpose())
a=np.array([[3,2,1],[7,6,5]])
print(a.shape)#(2,3)
#SO IN AXES WHEN I WRITE THE INDEX NUMBER OF COLUMN FIRST AND THEN ROW SO IT TRANSPOSE AS NORMAL
print(np.transpose(a,axes=(1,0)))#IT TRANSPOSE SAME LIKE A NORMAL
print(np.transpose(a,axes=(0,1)))#SAME LIKE A ORIGINAL ARRAY
print(a.T)#BUT I WILL NOT GIVE AXES ON THIS SYNTAX

#THREE DIMENSIONAL
a=np.arange(24)
a.resize(2,4,3)
print(a)
print(a.transpose())
print(a.transpose((1,2,0)))
print(a.T)

#ONE DIMENSIONAL
a=np.array([1,2,3,4,56,6])
print(np.transpose(a))#NO CHANGES BECAUSE TRANSPOSE FUNCTION IS USUALLY WORK ON ND-ARRAY

#SWAPAXES FUNCTION
#IT SWAP THE TWO AXES. IT IS USUALLY USED FOR THREE OR MORE THAN THREE DIMENSION ARRAY.
a=np.arange(36)
a.resize(2,6,3)
print(a)
print(a.shape)#(2,6,3)
print(a.swapaxes(1,2).shape)#(2,3,6)

#CONCATENATION
#IT CONCATENATE TWO OR MORE THAN TWO ARRAYS.
#WE SHOULD TAKE THE DIMENSION AND SHAPE OF AN ARRAY SUCH THAT ERROR WILL NOT OCCUR
#SYNTAX
#NP.CONCATENATE((ARRAYS),AXIS,OUT)
#ONE DIMENSIONAL ARRAY
#import numpy as np
a=np.array([3,2,1])
b=np.array([6,5,4,3,2])
c=np.array([8,7,6])
print(np.concatenate((a,b)))
print(np.concatenate((b,a)))
print(np.concatenate((c,a)))
print(np.concatenate((b,a,c)))
#OUT:TO SAVE THE ARRAYS IN ANOTHER ARRAY
d=np.ones(8)
print(d)
print(np.concatenate((a,b),out=d))
#OUTPUT WILL BE IN FLOAT TYPE BEACAUSE OF ONES FUNCTION

#TWO DIMENSIONAL
#SHAPE SHOULD BE SAME
a=np.arange(10)
a.resize(2,5)
print(a)
b=np.array([[4,3,5,6,2],[6,4,3,5,4]])
print(np.concatenate((a,b)))
d=np.ones((4,5))
print(d)
#OUT INTO D
print(np.concatenate((a,b),out=d))
#THE OUTPUT WILL BE IN FLOAT FORM BECAUSE OF ONES FUNCTION

#THREE DIMENSIONAL
a=np.array([[[4,3,2],[5,7,8]],[[3,2,1],[9,8,7]]])
print(a)
print(a.shape)
b=np.ones((2,2,3))
print(np.concatenate((a,b)))
d=np.zeros((4,2,3))
print(np.concatenate((a,b),out=d))
#THE OUTPUT WILL BE IN FLOAT FORM BECAUSE OF ZEROS FUNCTION

#AXIS
#IT SELECT THE AXES BY WHICH WE CAN CONCATENATE THE ARRAYS
#BY DEFAULT AXES IS ZERO
a=np.array([[4,3,2],[6,7,8]])
b=np.array([[3,2,1]])
print(np.concatenate((a,b)))
print(np.concatenate((a,b),axis=0))#SAME OUTPUT
#print(np.concatenate((a,b),axis=1))#ERROR
a=np.array([[2,1],[4,3]])
b=np.array([[8,7]])
print(np.concatenate((a,b.T),axis=1))
#WHEN AXIS IS 0 THEN NUMBER OF COLUMN MUST BE SAME AND WHEN AXIS IS EQUAL TO 1 SO THE  NUMBER OF ROWS MUST BE SAME

#VSTACK
#THIS FUNCTION CONCATENATE ARRAYS.FOR 1 DIMENSIONAL ARRAY THE NUMBER OF COLUMNS MUST BE SAME AND IT RETURN THE TWO DIMENSIONAL ARRAY AND FOR N-DIMENSIONAL ARRAY IT CONCATENATE WITH AXIS =0
#ONE DIMENSION
a=np.array([1,5,3,4])
b=np.array([5,6,7])
c=np.array([3,4,5,6])
#print(np.vstack((a,b)))#ERROR
print(np.vstack((a,c)))
#TWO DIMENSION
a=np.array([[3,2,1],[4,6,7]])
b=np.array([[3,2,1],[8,6,9],[0,5,3]])
print(np.vstack((a,b)))

#HSTACK
#HSTACK CONCATENATE THE ARRAY.
#FOR ONE DIMENSIONAL ARRAY IT RETURN ONE DIMENSIONAL ARRAY AND NO NEED OF SAME SHAPE
#FOR N-DIMENSIONAL ARRAY IT CONCATENATE AS AXIS IS EQUAL TO 1
#ONE DIMENSIONAL ARRAY
a=np.array([2,3,4,5])
b=np.array([7,6,5])
print(np.hstack((a,b)))
#TWO DIMENSION ARRAY
a=np.array([[4,3,2],[5,6,7]])
b=np.array([[2,1],[7,8]])
print(np.hstack((a,b)))

#SPLIT FUNCTION
#IT SPLIT THE ARRAY INTO SUB ARRAYS
#SYNTAX
#NP.SPLIT(ARRAY_NAME,SECTION,AXIS)
#WHEN WE GIVE THE SECTION SO WE SHOULD BE CARE THAT SECTIONED NUMBER MUST BE DIVISIBLE BY ARRAY_SIZE OTHER WISE WE WILL GET ERROR
#ONE DIMENSION
a=np.array([5,4,3,2,2,1])
print(np.split(a,3))
print(np.split(a,6))
#print(np.split(a,4))#ERROR

#TWO DIMENSION
a=np.array([[3,2,1],[8,9,6]])
print(np.split(a,2))
#print(np.split(a,3))

#VSPLIT
#IT SPLIT THE ARRAY WITH AXIS IS EQUALT TO 0
#VSPLIT IS ONLY WORK ON 2 OR MORE DIMNSIONAL ARRAY
a=np.array([[1,2,3,4],[5,6,7,8]])
print(np.vsplit(a,2))

#HSPLIT
#IT SPLIT THE ARRAY WITH AXIS IS EQUAL TO 0
#IT ALSO WORK ON 2 OR MORE DIMENAIONAL ARRAY
print(np.hsplit(a,2))
a=np.array([1,2,3,4])
#print(np.hstack(a,2))#ERROR

#import numpy as np
#INSERT METHOD
#IT INSERT THE VALUES INTO ARRAY
#SYNTAX
#NP.INSERT(ARRAY_NAME,OBJECT,VALUE,AXIS)
#BYDEFAULT AXIS IS NONE.
#IT WILL RETURN COPY OF AN ARRAY
#IF ARRAY IS IN INTEGAR FORM AND THE INSERTED VALUE IS FLOAT DATA TYPE SO FIRST IT WILL CHANGE FLOAT DATA TYPE INTO INT DATA TYPE AND THEN ADD THE VALUE
#IF AXIS IS NONE SO IT WILL RETURN 1DARRAY.FIRST IT WILL FLATTEN THE ARRAY AND THEN INSERT IT
#ONE DIMENSIONAL ARRAY
a=np.array([5,4,3,2,1])
print(a)
print(np.insert(a,2,20))
print(a)#IT WILL REMAIN SAME AS AN ORIGINAL ARRAY
print(np.insert(a,2,88.8))
#print(np.insert(a,3,'hasham'))#ERROR
#print(np.insert(a,2,3+4j))#ERROR
print(np.insert(a,2,'33'))#[5,4,33,3,2,1]
#WE CAN INSERT MORE THAN ONE OBJECT ONE AT A TIME
print(np.insert(a,(1,4),55))
#WE CAN ALSO INSERT THE LIST IN VALUES
print(np.insert(a,3,[7,8,9]))
#TWO DIMENSIONAL ARRAY
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.insert(a,2,77))
print(np.insert(a,4,55))
print(np.insert(a,(1,3,5),66))
#WE CAN ALSO INSERT THE LIST IN VALUES
print(np.insert(a,2,[1,2,3]))

#AXIS
#AXIS=0
a=np.array([[1,2],[4,3]])
#print(np.insert(a,2,[8,6,9],axis=0))#ERROR
print(np.insert(a,1,[8,9],axis=0))
#AXIS=1
print(np.insert(a,1,[8,9],axis=1))
#print(np.insert(a,1,[8,9,0],axis=1))#ERROR

#APPEND FUNCTION
#IT WILL INSEET THE NEW OBJECT IN THE LAST
#IT RETURN THE COPY OF THE ARRAY
#ONE DIMENSION
a=np.array([1,2,3,4])
print(np.append(a,5))
print(np.append(a,[9,8,7,6]))

#TWO DIMENSIONAL ARRAY
a=np.array([[1,2],[3,4]])
print(a)
print(np.append(a,[8,9]))
print(a)
print(np.append(a,[[8,9]],axis=0))
print(np.append(a,[[8],[9]],axis=1))
#print(np.append(a,[[8],[9]],axis=0))#ERROR

#DELETE FUNCTION
#IT DELETE A ELEMENT
#IT WILL RETURN COPY OF AN ARRAY
#ONE DIMENSIONAL ARRAY
a=np.array([1,2,3,4])
print(np.delete(a,2))#[1,2,4]
print(a)#[1,2,3,4]
print(np.delete(a,3))

#TWO DIMENSIONAL ARRAY
a=np.array([[1,2],[3,4]])
print(np.delete(a,2))#[1,2,4]
print(np.delete(a,3))#[1,2,3]
a=np.array([[1,2],[3,4],[5,6]])
print(np.delete(a,2,axis=0))#[[1,2],[3,4]]
#print(np.delete(a,3,axis=0))#ERROR
print(np.delete(a,1,axis=1))
#print(np.delete(a,2,axis=1))#ERROR


[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[2 3 4 5 4 3]
[2 5 3 4 4 3]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(2, 4)
[[1 7]
 [2 6]
 [3 5]
 [4 4]]
(2, 4)
[[0 1 

## **MATRIX**

In [30]:
#MATRIX: 2D ARRAY OR A RECTANGULAR ARRAY OF DATA
#THE HORIZONTAL ENTRIES ARE CALLED ROWS.
#THE VERTICAL ENTRIES ARE CALLED COLUMN.
#MATRIX OPERATION
#ADDITION
#MULTIPLICATION
#TRANSPOSE
#ADDITION OF A MATRICES
#FOR ADDITION AND SUBTRACTION THE NUMBER OF ROWS AND COLUMN MUST BE EQUAL
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+b)
print(a-b)
#MULTIPLICATION OF A MATRICES
# "*" SYMBOL IS USED FOR ELEMENT TO ELEMENT MULTIPLICATION.FOR MATRIX MULTIPLICATION ,WE USED .DOT()
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a*b)#ELEMENT TO ELEMENT MULTIPLICATION
print(a.dot(b))
#help(np.dot)
c=np.array([[1,1],[1,1]])
print(a.dot((b),out=c))
print(c)
#TRANSPOSE OF A MATRIX
a=np.array([[1,2],[3,4]])
print(a.T)

#MATRIX CLASS
#IT CONVERT DATA INTO MATRIX
a=np.matrix("1 2;3 4")
print(a)
print(a.dtype)#int
#b=np.matrix(1 2;3 4)
#print(b)#ERROR
b=np.matrix([[1,2],[3,4]])
print(b)
a=np.matrix([[5,6],[7,8]])
#ADDITION OF A MATRIX
print(a+b)
#MULTIPLICATION OF A MATRIX
# WE CAN USE "*" FOR MULTIPLICATION IN A MATRIX CLASS
print(a*b)
print(a.dot(b))
#TRANSPOSE OF A MATRIX
print(b.T)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
int64
[[1 2]
 [3 4]]
[[ 6  8]
 [10 12]]
[[23 34]
 [31 46]]
[[23 34]
 [31 46]]
[[1 3]
 [2 4]]


## **LINEAR ALGEBRA**

In [33]:
#LINEAR ALGEBRA
#IT IS THE FINCTION WHICH IS USED TO
#1)FIND INVERSE OF A MATRIX
#2)POWER THE MATRIX
#3)SOLVE THE LINEAR EQUATION
#4)FIND DETERMINANT OF A MATRIX

#INVERSE OF A MATRIX
#SYNTAX
#NUMPY.LINALG.INV(ARRAY_NAME)
#IT RETURN COPY OF A MATRIX
#THE MATRIX MUST BE  SQUAREMATRIX OTHERWISE THE OUTPUT WILL BE ERROR
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))
print(a)#ORIGINAL ARRAY
a=np.matrix([[1,2],[3,4]])
print(np.linalg.inv(a))
b=np.array([1,2,3,4])
#print(np.linalg.inv(b))#ERROR BECAUSE DIMENSION OF ARRAY ATLEAST 2D
#A.INVERSE OF A=APPROX IDENTITY MATRIX
a=np.array([[1,2],[3,4]])
b=np.linalg.inv(a)
print(b)
print(np.dot(a,b))
print(np.allclose(np.dot(a,b),np.eye(2)))#TRUE
a=np.array([[1,2,3],[4,5,6]])
#print(np.linalg.inv(a))#ERROR 
#BECAUSE INVERSE FUNCTION IS ONLY WORK ON SQUARE MATRIX
a=np.array([[[1,2],[3,4]],[[7,8],[9,10]]])
print(a)
print(np.linalg.inv(a))#IN 3D ARRAY THIS FUNCTION  INVERSE ALL MATRIX

#POWER OF A MATRIX
#SYNATX
#NUMPY.LINALG.MATRIX_POWER(ARRAY_NAME,NUMBER)
#IF N=0(OUTPUT WILL BE AN IDENTITY MATRIX)
#IF N<1(FIRST THE MATRIX CONVERTED INTO INVERSE AND THEN ABS(N) WILL BE THE POWER)
#THE MATRIX MUST BE SQUARE MATRIX
#a=np.array([1,2,3])
#print(np.linalg.matrix_power(a,2))
#ERROR BECAUSE MATRIX ATLEAT 2DIMENSIONAL
a=np.array([[1,2],[3,4]])
print(np.linalg.matrix_power(a,2))
print(a)#ORIGINAL ARRAY
print(np.linalg.matrix_power(a,-3))
print(np.linalg.matrix_power(a,0))#IDENTITY MATRIX

#SOLVE THE EQUATION
#SYNTAX 
#NUMPY.LINALG.SOLVE(A,B)
#3x+y=9
#x+2y=8
#AX=B
#A MUST BE  A SQUARE MATRIX OF COEFFICIENT
#B IS ONE DIMENSIONAL ARRAY
#X IS THE VALUES OF VARIABLE CALCULATED BY NUMPY AND GIVE US THE OUTPUT
a=np.array([[3,1],[1,2]])
b=np.array([9,8])
print(np.linalg.solve(a,b))
#print(np.linalg.solve(b,a))#ERROR
#WE CAN ALSO SOLVE 3x3 MATRIX 

#DETERMINANT OF A MATRIX
#SYNTAX
#NUMPY.LINALG.DET(ARRAY_NAME)
a=np.array([[1,2],[3,4]])
print(np.linalg.det(a))


[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
True
[[[ 1  2]
  [ 3  4]]

 [[ 7  8]
  [ 9 10]]]
[[[-2.   1. ]
  [ 1.5 -0.5]]

 [[-5.   4. ]
  [ 4.5 -3.5]]]
[[ 7 10]
 [15 22]]
[[1 2]
 [3 4]]
[[-14.75    6.75 ]
 [ 10.125  -4.625]]
[[1 0]
 [0 1]]
[2. 3.]
-2.0000000000000004


## **UNIVERSAL FUNCTION OR UFUNC**

In [34]:
#SQRT=GIVE SQUARE ROOT OF EACH ENTRIES
a=np.array([1,2,3,4,5])
print(np.sqrt(a))
#I CAN ALAO SAVE THE SQUARE ROOT ARRAY IN VARIABLE 
c=np.ones(5)
print(np.sqrt(a,c))
print(c)
print(a)#REMAIN AS ORIGIN
#EXP=GIVE EXPONENT OF EACH ENTRIES LIKE e*1,e*2.......
print(np.exp(a))
#MAXIMUM=COMPARE TWO ARRAYS AND PRINT MAXIMUM VALUE
b=np.array([2,2,2,1,7])
print(np.maximum(a,b))
c=np.array([2,9,8,7,5])
print(np.maximum(a,b,c))#ONLY COMPARE A AND B
#MINIMUM=GIVE MINIMUM VALUE
print(np.minimum(a,b))
#SQUARE
#PRINT SQUARE OF EVERY ELEMENT
print(np.square(a))
#ABS
#ABS OR ABSOLUTE OR FABS PRINT THE DISTANCE OF AN ELEMEMT FROM ZERO
b=np.array([1,0,3,-4,-7]) 
print(np.abs(b))
#SIGN
#SIGN GIVE WHICH ELEMENT IS POSITIVE AND WHICH ONE IS NEGATIVE AND WHICH ONE IS ZERO
#IT PRINT 1 FOR POSITIVE VALUE AND -1 FOR NEGATIVE VALUE AND 0 FOR 0
print(np.sign(b))
#CEIL
#IT PRINT THE ROUND TO NEXT NUMBER
c=np.array([1,2,3.3,6.9,5.5])
print(np.ceil(c))
#FLOOR
#IT PRINT THE ROUND TO PREVIOUS NUMBER
print(np.floor(c))
#RINT=IT PRINT THE ROUND TO NEAREST NUMBER
print(np.rint(c))
#isnan
#IT WILL PRINT TRUE IN THE PLACE OF NAN VALUES OTHERWISE IT WILL PRINT TRUE
#TO CONVERT A DATA INTO NAN IT IS COMPULSORY THAT A DATA MUAT BE IN FLOAT FORM
d=np.array([2,3,5,7],dtype=float)
print(np.isnan(d))
d[2]=np.nan
print(d)
print(np.isnan(d))

#ADD
a=np.array([2,3,1,5])
b=np.array([8,9,5,2])
print(np.add(a,b))
#SUBTRACT
a=np.array([2,3,1,5])
b=np.array([8,9,5,2])
print(np.subtract(a,b))
#MULTIPLY
a=np.array([2,3,1,5])
b=np.array([8,9,5,2])
print(np.multiply(a,b))
#DIVIDE
a=np.array([2,3,1,5])
b=np.array([8,9,5,2])
print(np.divide(a,b))
#MOD
a=np.array([2,3,1,5])
b=np.array([8,9,5,2])
print(np.mod(a,b))
#POWER
a=np.array([2,3,1,5])
b=np.array([8,9,5,2])
print(np.power(a,b))
#fmin=IT GIVES MINIMUM VALUE BUT IT IGNORES NAN AND PRINT THE VALUE IN THE COMPARISION
a=np.array([1,2,3],dtype=float)
a[2]=np.nan
print(a)
b=np.array([0,3,2])
print(np.fmin(a,b))
#copysign=IT CHANGE THE SIGN WITH RESPECT TO COMPARISION ARRAY 
a=np.array([1,2,-3])
b=np.array([-4,-5,6])
print(np.copysign(a,b))#[-1,-2,3]
print(np.copysign(b,a))#[4,5,-6]


[1.         1.41421356 1.73205081 2.         2.23606798]
[1.         1.41421356 1.73205081 2.         2.23606798]
[1.         1.41421356 1.73205081 2.         2.23606798]
[1 2 3 4 5]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[2 2 3 4 7]
[2 2 3 4 7]
[1 2 2 1 5]
[ 1  4  9 16 25]
[1 0 3 4 7]
[ 1  0  1 -1 -1]
[1. 2. 4. 7. 6.]
[1. 2. 3. 6. 5.]
[1. 2. 3. 7. 6.]
[False False False False]
[ 2.  3. nan  7.]
[False False  True False]
[10 12  6  7]
[-6 -6 -4  3]
[16 27  5 10]
[0.25       0.33333333 0.2        2.5       ]
[2 3 1 1]
[  256 19683     1    25]
[ 1.  2. nan]
[0. 2. 2.]
[-1. -2.  3.]
[ 4.  5. -6.]


## **STATISTICS**

In [35]:

import numpy as np
from scipy import stats
a=np.array([1,2,2,2,2,3,4,99,77])
#MEAN:AVERAGE OF ALL NUMBERS
print(np.mean(a))#21.3333
#STANDARD DEVIATION:In statistics, the standard deviation is a measure of the amount of variation or dispersion of a set of values. A low standard deviation indicates that the values tend to be close to the mean of the set, while a high standard deviation indicates that the values are spread out over a wider range.
print(np.std(a))#36.01
#MEDIAN:IF THE TOTAL NUMBER OF ELEMENTS ARE ODD THEN THE MIDDLE VALUE ID MEDIAN AND IF NUMBER OF ELEMENTS ARE EVEN THEN THE MEAN OF TWO MIDDLE VALUE IS MEDIAN
print(np.median(a))#2.0
b=np.array([1,2,3,4])
print(np.median(b))
#The term variance refers to a statistical measurement of the spread between numbers in a data set. More specifically, variance measures how far each number in the set is from the mean and thus from every other number in the set.
print(np.var(a))#1297.33
print(np.sum(a))#192
print(np.prod(a))#1463616
print(np.min(a))#1
print(np.max(a))#99
print(stats.mode(a))#mode-array[2] and count-array[4]
#CUMSUM:SUM THE ELEMENT COLUMN WISE [1,1+2,1+2+4,1+2+4+7.....]
a=np.array([1,2,4,7])
print(np.cumsum(a))
#CUMPROD:PRODUCT THE ELEMENT COLUMN WISE [1,1*2,1*2*4,1*2*4*7,...]
print(np.cumprod(a))
#AXIS
#AXIS=0:IT WILL APPLY THE OPERATION COLUMN WISE
#AXIS=1:IT WILL APPLY THE OPERATION ROWS WISE.
a=np.array([[1,2],[3,4]])
print(a.sum(axis=0))#[4,6]
print(a.sum(axis=1))#[3,7]
print(a.sum())#10



21.333333333333332
36.018513757973594
2.0
2.5
1297.3333333333333
192
1463616
1
99
ModeResult(mode=array([2]), count=array([4]))
[ 1  3  7 14]
[ 1  2  8 56]
[4 6]
[3 7]
10
